services:
  - type: web
    name: dotix-job-scheduler-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dotix-db
          property: connectionString
      - key: WEBHOOK_URL
        generate:
          length: 32

databases:
  - name: dotix-db
    databaseName: dotix
    user: dotixuser
    plan: free
